version: 2

# note: dependabot PRs have their own sets of secrets (they can't use the GH-A secrets)
updates:
  # bump submodules.
  # updates a submodule to the latest commit on the branch given in .gitmodules.
  # if branch not given, then it defaults to the main/master branch.
  - package-ecosystem: gitsubmodule
    schedule:
      interval: "weekly"
    directory: /
    labels:
      - "dependencies"
      - "changelog:omit"

  # submit a PR for bumping GH-A dependencies
  - package-ecosystem: github-actions
    schedule:
      interval: "weekly"
    directory: /
    labels:
      - "dependencies"
      - "changelog:omit"
