name: buildsetup
description: "Run firesim's build-setup.sh. Used only for GH-hosted CI containers."

runs:
  using: "composite"
  steps:
    - run: |
        source /opt/conda/etc/profile.d/conda.sh
        conda activate firesim
        ./build-setup.sh
        # All actions that run in a GH-hosted container source env.sh before
        # running their jobs. This ensures conda is in the runner's path, which
        # is not the case by default.
        sed -i "1s;^;export PATH=$PATH:/opt/conda/condabin\n;" env.sh
      shell: bash
