name: firesim-publish-scala-doc

on:
  # On pushes to these branches / tags publish the scala doc to GH pages.
  push:
    branches:
      - main
      - stable
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'
  # On PRs to stable or main, check that the docs build correctly without publishing
  pull_request:
    branches:
      - main
      - stable

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_08012023 }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_08012023 }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION_08012023 }}
  FIRESIM_PEM: ${{ secrets.FIRESIM_PEM_08012023 }}
  FIRESIM-REPO-DEP-KEY: ${{ secrets.BARTENDER_PRIVATE_SSH_KEY }}
  MANAGER_FIRESIM_LOCATION: "~/firesim"
  LANG: "en_US.UTF-8" # required by SBT when it sees boost directories
  LANGUAGE: "en_US:en"
  LC_ALL: "en_US.UTF-8"

jobs:
  change-filters:
    name: filter-jobs-on-changes
    runs-on: ubuntu-20.04
    # Queried by downstream jobs to determine if they should run.
    outputs:
      needs-scala-doc: ${{ steps.filter.outputs.scala-docs }}

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            scala-docs:
              - '**/build.sbt'
              - '**/*.scala'

  publish-scala-doc:
    name: publish-scala-doc
    needs: change-filters
    if: needs.change-filters.outputs.needs-scala-doc == 'true'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/repo-setup
      - uses: ./.github/actions/build-scala-doc
      - name: "Push ScalaDoc to remote"
        if: ${{ github.event_name == 'push' }}
        uses: ./.github/actions/push-scaladoc-to-ghpages
